# List of project's own icon files
# This file is generated by update_icon_list.sh
# WARNING! All changes made in this file will be lost!

set(_PNG_FILES
)

set(_SVG_FILES
icons/breeze/actions/16/kexiform-web-browser.svg
icons/breeze/actions/22/kexiform-web-browser.svg
icons/breeze/actions/24/kexiform-web-browser.svg
)

set(_FILES ${_PNG_FILES} ${_SVG_FILES})
