# List of project's own icon files
# This file is generated by update_icon_list.sh
# WARNING! All changes made in this file will be lost!

set(_PNG_FILES
)

set(_SVG_FILES
)

set(_FILES ${_PNG_FILES} ${_SVG_FILES})
